### ISSUE TITLE
English Translate: tarunon

### ISSUE THREAD

**Issue by kishida** [HackerTackle/HackerTackle.github.io#130]
None->Nothing?確認中
「typeは大文字スタートのほうが良さそう」

**Comment by matsumana** [comment]
> None->Nothing?確認中

Not fixed yet.

> 「typeは大文字スタートのほうが良さそう」

fixed in #136

**Comment by kishida** [comment]
> Nothing, Mu->Empty

とのことでした

**Comment by matsumana** [comment]
> とのことでした

Are my understandings correct?

# AsIs

- None, Type and program
- I will ponder on the meaning of "Mu," or nothingness

# ToBe

- Empty, Type and program
- I will ponder on the meaning of Empty or nothingness
